### PR TITLE
update message prefix & copyright

### PR DESCRIPTION
**Pull request by digicontributer**
The message prefix shouldn't change based on network and I've updated to the correct prefix as Per my comments on #1

### CODE REVIEW

**Review by ycagel — APPROVED** [review]
cACK. Thanks Gary!

**Review by ycagel — APPROVED** [review]
cACK. Thanks Gary!

**Review by gto90 — APPROVED** [review]
ACK

Thanks for this PR @digicontributer !

**Review by SmartArray — APPROVED** [review]
ACK

Thank you so much Gary

**Pull request merged**
