### PR TITLE
bugfix: Updated Rosetta Documentation & Resolved Rosetta CLI tests issue

### PR DESCRIPTION
**Pull request by gto90**
* Made minor updates and reviewed README.md documentation to ensure they are correct.
* Resolved an issue that caused the Coinbase rosetta-cli functional test suite to fail.

### CODE REVIEW

**Review by ycagel — DISMISSED** [review]
aCK. Great job GTO! Thanks for all your efforts!

**Review by JaredTate — DISMISSED** [review]
ACK

**Comment by ycagel** [comment]
When attempting to do the regtest, the command line did not work. I had to use the following:

sudo docker build -t digibyte/rosetta:latest . --build-arg use_regtest=1

Thanks to @j50ng for locating this. I believe the documentation will need to be updated with this in all instances.

**Review by ycagel — APPROVED** [review]
Thanks for all your hard work @gto90! 

aCK

**Review by j50ng — APPROVED** [review]
ACK

Great work here with the fixes.  Zero issues/warnings/errors!

**Review by j50ng — APPROVED** [review]

**Review by j50ng — APPROVED** [review]

**Review by JaredTate — APPROVED** [review]
aCK. Awesome work GTO! We need to make a note to change regtest ports in 8.22 core as well.

**Comment by SmartArray** [comment]
ACK, probably too late. 😔

Thanks for your consistent hard work @gto90 and all the others who were involved!! I am really glad that this rosetta-server looks more stable and reliable now.

**Pull request merged**
